In [1]:
import numpy as np

In [2]:
a = np.array([[12, 34, 41], [54, 62, 18], [72, 84, 96]], np.int16)

In [3]:
a

array([[12, 34, 41],
       [54, 62, 18],
       [72, 84, 96]], dtype=int16)

In [4]:
a.size

9

In [5]:
a.shape

(3, 3)

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int16')

In [8]:
a[2, 2] #this is how we index a particular element in the array

96

In [9]:
b = a[0,:]

In [10]:
b

array([12, 34, 41], dtype=int16)

In [11]:
b.shape

(3,)

In [12]:
b[2] = 88 # this is how we reassign another value to a memner in the array

In [13]:
a[2, 2] = 99

In [14]:
a

array([[12, 34, 88],
       [54, 62, 18],
       [72, 84, 99]], dtype=int16)

In [15]:
b

array([12, 34, 88], dtype=int16)

## Matrix vs. Array:

### 1. Matrix

In [16]:
a = np.mat('[12 34 41;52 64 72]') # create matrix a

In [17]:
a

matrix([[12, 34, 41],
        [52, 64, 72]])

In [18]:
type(a)

numpy.matrixlib.defmatrix.matrix

In [19]:
a.I # inverse of matrix 'a'

matrix([[-0.05885099,  0.03258602],
        [ 0.01490374, -0.00181295],
        [ 0.02925572, -0.00803395]])

In [20]:
b = np.mat('[84 92]') # create matrix b

In [21]:
b

matrix([[84, 92]])

In [22]:
type(b)

numpy.matrixlib.defmatrix.matrix

In [23]:
b.T # transpose of 'b'

matrix([[84],
        [92]])

In [24]:
a.T*b.T

matrix([[ 5792],
        [ 8744],
        [10068]])

### 2. Array

In [25]:
from scipy import linalg

In [26]:
c = np.array([[12,34,41],[52,64,72],[84,91,98]]) # create array 'c'

In [27]:
c

array([[12, 34, 41],
       [52, 64, 72],
       [84, 91, 98]])

In [28]:
type(c)

numpy.ndarray

In [29]:
linalg.inv(c) # calculate the inverse of a matrix

array([[-0.10752688,  0.15322581, -0.06758833],
       [ 0.3655914 , -0.87096774,  0.48694316],
       [-0.24731183,  0.67741935, -0.38402458]])

In [30]:
d2 = np.array([[2, 12, 28]]) # create 2D array

In [31]:
d2

array([[ 2, 12, 28]])

In [32]:
type(d2)

numpy.ndarray

In [33]:
c*d2 # this is not a matrix multiplication

array([[  24,  408, 1148],
       [ 104,  768, 2016],
       [ 168, 1092, 2744]])

In [34]:
c.dot(d2.T) # this is matrix multiplication using for product function

array([[1580],
       [2888],
       [4004]])

In [36]:
d1 = np.array([2,12,28]) # this is 1D array

In [37]:
d1

array([ 2, 12, 28])

In [38]:
type(d1)

numpy.ndarray

In [39]:
d1.T # this is not a matrix transpose

array([ 2, 12, 28])

In [40]:
c.dot(d1) # dot product of two arrays

array([1580, 2888, 4004])